apps/bookapo_admin/lib/bookapo_admin_web/router.ex
defmodule BookapoAdminWeb.Router do
  use BookapoAdminWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/admin", BookapoAdminWeb do
    pipe_through [:browser, :protected]

    get "/", AdminController, :show

    resources "/books", BookController, only: [:new, :create, :edit, :update, :delete]
    resources "/categories", CategoryController, only: [:new, :create, :edit, :update, :delete]
    resources "/authors", AuthorController, only: [:new, :create, :edit, :update, :delete]
  end

  scope "/admin" do
    pipe_through :browser

    pow_session_routes()
  end

  scope "/admin", Pow.Phoenix, as: "pow" do
    pipe_through [:browser, :protected]
    resources "/registration", RegistrationController, singleton: true, only: [:edit, :update, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookapoAdminWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  #if Mix.env() in [:dev, :test] do
  #  import Phoenix.LiveDashboard.Router

  #  scope "/" do
  #    pipe_through :browser
  #    live_dashboard "/dashboard", metrics: BookapoAdminWeb.Telemetry
  #  end
  #end
end

apps/bookapo_admin/lib/bookapo_admin_web/views/layout_view.ex
defmodule BookapoAdminWeb.LayoutView do
  use BookapoAdminWeb, :view
end

apps/bookapo_admin/lib/bookapo_admin_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>BookapoAdmin · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>

            <%= if Pow.Plug.current_user(@conn) do %>
              <li><%= link "Return to website", to: "/" %></li>
              <li><%= link "New Book", to: Routes.book_path(@conn, :new) %></li>
              <li><%= link "New Author", to: Routes.author_path(@conn, :new) %></li>
              <li><%= link "New Category", to: Routes.category_path(@conn, :new) %></li>
              <li><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></li>
              <li><%= link "Admin Dashboard", to: Routes.admin_path(@conn, :show) %></li>
            <% else %>
              <li><%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %></li>
            <% end %>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>